pipeline {
 
  agent any

  environment {
        POM_VERSION = ""
    }

   stages {

      stage('Teste') {

          agent {
                docker { 
                    image 'maven' 
                    }
          }
          steps {

                sh "mvn test"
            }
       }
    }


}