pipeline {
 
  agent any

  environment {
        POM_VERSION = ""
    }

   stages {

      stage('Teste') {

        
          steps {

                sh "mvn test"
            }
       }
    }


}