pipeline {
 
 agent any

     stages {

        stage('Teste') {

            agent {
                docker { image 'maven' }
            }
            steps {

                sh "mvn clean install"
            }
        }
    }


}